<a href="https://colab.research.google.com/github/azizdaim/epl-data-analysis/blob/main/epl_eda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

df = pd.read_csv('epl_final.csv')
df['MatchDate'] = pd.to_datetime(df['MatchDate'])

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9380 entries, 0 to 9379
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Season             9380 non-null   object
 1   MatchDate          9380 non-null   datetime64[ns]
 2   HomeTeam           9380 non-null   object
 3   AwayTeam           9380 non-null   object
 4   FullTimeHomeGoals  9380 non-null   int64
 5   FullTimeAwayGoals  9380 non-null   int64
 6   FullTimeResult     9380 non-null   object
 7   HalfTimeHomeGoals  9380 non-null   int64
 8   HalfTimeAwayGoals  9380 non-null   int64
 9   HalfTimeResult     9380 non-null   object
 10  HomeShots          9380 non-null   int64
 11  AwayShots          9380 non-null   int64
 12  HomeShotsOnTarget  9380 non-null   int64
 13  AwayShotsOnTarget  9380 non-null   int64
 14  HomeCorners        9380 non-null   int64
 15  AwayCorners        9380 non-null   int64
 16  HomeFouls          9380 non-null   int64
 17  AwayFouls          9380 non-null   int64
 18  HomeYellowCards    9380 non-null   int64
 19  AwayYellowCards    9380 non-null   int64
 20  HomeRedCards       9380 non-null   int64
 21  AwayRedCards       9380 non-null   int64
dtypes: datetime64[ns](1), int64(16), object(5)
memory usage: 1.6+ MB

In [2]:
df['FullTimeResult'].value_counts()

FullTimeResult
H    4299
A    2768
D    2313
Name: count, dtype: int64

In [3]:
df['FullTimeResult'].value_counts(normalize=True)

FullTimeResult
H    0.458316
A    0.295096
D    0.246588
Name: proportion, dtype: float64

In [4]:
df.groupby('Season')['FullTimeResult'].value_counts(normalize=True)

Season   FullTimeResult
2000/01  H                 0.484211
         D                 0.265789
         A                 0.250000
2001/02  H                 0.434211
         A                 0.300000
                             ...
2023/24  A                 0.323684
         D                 0.215789
2024/25  H                 0.411429
         A                 0.337143
         D                 0.251429
Name: proportion, Length: 75, dtype: float64